#!/usr/bin/env bash

########################
## Base Configuration ##
########################


hlog "Bootstrapping"

# Create a .bin directory if there is none
if [[ ! -d "$HOME/.bin/" ]]; then
  log "creating .bin directory"
  mkdir "$HOME/.bin"
fi

# Make sure homebrew is installed
if ! command -v brew >/dev/null; then
  log "installing homebrew"
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  export PATH="/usr/local/bin:$PATH"
else
  log "homebrew is already installed"
fi
