#!/bin/sh

# Editor Setup
# Install Neovim and all plugin dependencies

header_log "Configuring Editor"

brew tap neovim/neovim
brew_upgrade_or_install "neovim/neovim/neovim"

# Completion plugin Deoplete dependencies
log "installing neovim python clients"
pip2 install neovim
pip3 install neovim

# Tagbar
brew_upgrade_or_install "ctags"

# An alternatirve of Ag, used for CtrlP
brew_upgrade_or_install "ripgrep"

log "installing vim-plug"
curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

log "installing all Neovim plugins"
nvim +PlugInstall +qall

log "installing Go Binaries for vim-go"
nvim +GoInstallBinaries +qall

log "updating plugins"
nvim +UpdateRemotePlugins +qall

log "installing editor/terminal fonts"
brew tap caskroom/fonts
brew cask install font-droid-sans-mono
brew cask install font-droid-sans-mono-for-powerline
