#!/bin/sh

# Go Setup
# Install the latest version of go and set the GOPATH directory

header_log "Go Setup"

brew_upgrade_or_install "go" --with-cc-all

log "creating GOPATH directory in ~/Projects/go"
mkdir -p ~/Projects/ongoing/go/bin
mkdir ~/Projects/ongoing/go/src
mkdir ~/Projects/ongoing/go/pkg

log "install some basic dependencies"
go get -u github.com/nsf/gocode
