#!/bin/sh

# macOS Setup
# Configure macOS how I like it!

computer_name = "zelda"

header_log "macOS Defaults"
highlight_color = "0.764700 0.976500 0.568600"
screenshots_dir = "${HOME}/Desktop/Screenshots"

log "setting up the computer name to $computer_name"
sudo scutil --set ComputerName $computer_name
sudo scutil --set HostName $computer_name
sudo scutil --set LocalHostName $computer_name
sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName -string $computer_name

log "setting highlight color to $highlight_color"
defaults write NSGlobalDomain AppleHighlightColor -string $highlight_color

log "expand save panel by default"
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode2 -bool true

log "expand print panel by default"
defaults write NSGlobalDomain PMPrintingExpandedStateForPrint -bool true
defaults write NSGlobalDomain PMPrintingExpandedStateForPrint2 -bool true

log "automatically quit printer app once the print jobs complete"
defaults write com.apple.print.PrintingPrefs "Quit When Finished" -bool true

log "setting up trackpad tap to click"
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true
defaults -currentHost write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
defaults write NSGlobalDomain com.apple.mouse.tapBehavior -int 1

log "require password immediatelly after sleep or screen saver begins"
defaults write com.apple.screensaver askForPassword -int 1
defaults write com.apple.screensaver askForPasswordDelay -int 0

log "save screenshots under $screenshots_dir"
mkdir -p $screenshots_dir
defaults write com.apple.screencapture location -string $screenshots_dir

log "save screenshots in PNG format"
defaults write com.apple.screencapture type -string "png"

log 'setting up finder defaults'

log "set Desktop as default location for new Finder windows"
defaults write com.apple.finder NewWindowTarget -string "PfLo"
defaults write com.apple.finder NewWindowTargetPath -string "file://${HOME}/"

log "show icons for hard drives, servers, and removable media on the desktop"
defaults write com.apple.finder ShowExternalHardDrivesOnDesktop -bool true
defaults write com.apple.finder ShowHardDrivesOnDesktop -bool true
defaults write com.apple.finder ShowMountedServersOnDesktop -bool true
defaults write com.apple.finder ShowRemovableMediaOnDesktop -bool true

log "allow text selection in Quick Look"
defaults write com.apple.finder QLEnableTextSelection -bool true

# Four-letter codes for the other view modes: `icnv`, `clmv`, `Flwv`
log "use list view in all Finder windows by default"
defaults write com.apple.finder FXPreferredViewStyle -string "Nlsv"

log "disable warning before emptying the tash"
defaults write com.apple.finder WarnOnEmptyTrash -bool false

log "empty trash securely by default"
defaults write com.apple.finder EmptyTrashSecurely -bool true

log "don't rearrange Spaces based on recent use"
defaults write com.apple.dock mru-spaces -bool false

log "automatically hide and show the Dock"
defaults write com.apple.dock autohide -bool true

# Hot corners
# Possible values:
#  0: no-op
#  2: Mission Control
#  3: Show application windows
#  4: Desktop
#  5: Start screen saver
#  6: Disable screen saver
#  7: Dashboard
# 10: Put display to sleep
# 11: Launchpad
# 12: Notification Center

log "configuring hot corners"
# Top left screen corner → Launchpad
defaults write com.apple.dock wvous-tl-corner -int 11
defaults write com.apple.dock wvous-tl-modifier -int 0
# Top right screen corner → Desktop
defaults write com.apple.dock wvous-tr-corner -int 4
defaults write com.apple.dock wvous-tr-modifier -int 0

log "done"
