#!/usr/bin/env bash

################
## Node Setup ##
################

# TODO: Get the latest version dynamically
node_version="0.10"

# brew install node
brewui 'nvm'
source $(brew --prefix nvm)/nvm.sh

log "installing Node $node_version"
nvm install "$node_version"

log "setting node $node_version as the global default"
nvm alias default "$node_version"
