#!/usr/bin/env bash

#################
## Shell Setup ##
#################

hlog "Shell Configuration"

brewui 'bash'
brewui 'bash-completion'

# Add the new bash shell to the allowed shells list
if ! grep $(which bash) /etc/shells; then
  log 'adding bash to /etc/shells'
  printf "%s\n" "$(which bash)" | sudo tee -a /etc/shells
fi

# Change the default shell
if [[ "$SHELL" != $(which bash) ]]; then
  log 'changing shell to bash'
  chsh -s $(which bash)
fi
