#!/usr/bin/env bash

#######################
## Utility Functions ##
#######################

expand_alias() {
  brew info "$1" 2>/dev/null | head -1 | awk '{gsub(/:/, ""); print $1}'
}

is_installed() {
  local name="$(expand_alias "$1")"
  brew list -1 | grep -Fqx "$name"
}

is_upgradable() {
  local name="$(expand_alias "$1")"
  brew outdated --quiet "$name" >/dev/null
  [[ $? -ne 0 ]]
}

brewui() {
  if is_installed "$1"; then
    if is_upgradable "$1"; then
      log "upgrading $1"
      brew upgrade "$@"
    fi
  else
    log "installing $1"
    brew install "$@"
  fi
}

caski() {
  log "installing $1"
  brew cask install "$@"
}
