#!/usr/bin/env bash

########################
## Base Configuration ##
########################

# Create a .bin directory if there is none
if [[ ! -d "$HOME/.bin/" ]]; then
  log "Creating .bin directory"
  mkdir "$HOME/.bin"
  log "Done"
fi

# Make sure homebrew is installed
if ! command -v brew >/dev/null; then
  log "Installing Homebrew"
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  export PATH="/usr/local/bin:$PATH"
  log "Done"
else
  log "Homebrew is already installed"
fi
