#!/usr/bin/env bash

####################
## Homebrew Setup ##
####################

# Update formulae
log 'Updating homebrew formulae'
brew update
log 'Done'

# Upgrade installed formulae
log 'Upgrading homebrew installed packages'
brew upgrade
log 'Done'

# Git and GitHub add-ons
brewui 'git'
brewui 'hub'

# Dev utilities
brewui 'redis'
# brewui 'postgres' # Using PostgresApp instead
brewui 'the_silver_searcher'
brewui 'vim' --override-system-vi
brewui 'ctags'
brewui 'tmux'
brewui 'reattach-to-user-namespace'
brewui 'imagemagick' --with-webp
brewui 'qt'
brewui 'watch'

# OpenSSL unlink and link to avoid conflicts with Homebrew
brewui 'openssl'
brew unlink openssl && brew link openssl --force

# Install Heroku CLI and extra utitlites
brewui 'heroku-toolbelt'
heroku plugins:install https://github.com/ddollar/heroku-config.git

# More nice utitlities
brewui 'libidn'
brewui 'wget' --with-iri
brewui 'ringojs'
brewui 'narwhal'
brewui 'webkit2png'
brewui 'rename'
brewui 'rhino'

# Remove outdated packages
log 'Removing outdated packages'
brew cleanup
log 'Done'
