#!/usr/bin/env bash

################
## Cask Setup ##
################

log 'Installing Cask'
brew tap caskroom/cask
brew install brew-cask
log 'Done'

# Browsers
caski google-chrome
caski firefox
caski opera

# Editors
caski atom

# Utilities
caski iterm2
caski postgres
caski dropbox
caski evernote
caski slack
caski mailbox
caski pgadmin3
caski screenhero
caski skype
caski caffeine

# Fun
caski spotify
