#!/usr/bin/env bash

# Welcome! Lets build an awesome dev box together.
# Run me and then go eat a bagel.
#
#
# This script is heavily influenced by the laptop project from the great
# thoughtbot team and the fantastic Mathias Bynens' dot files - by "heavily
# influenced" I mean a lot of copypasta going on :-)
#
# Many thanks to both thoughtbot and Mathias Bynens.
#
# - https://github.com/thoughtbot/laptop
# - https://github.com/mathiasbynens/dotfiles



###########################
## Sudo | Error Handling ##
###########################

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# Kill execution if something goes wrong. TODO: exit more gracefully.
trap 'ret=$?; test $ret -ne 0 && printf "failed\n\n" >&2; exit $ret' EXIT
set -e

# Letting you know bagel started
printf "\n\n\n#########################\nSTART\n#########################\n\n\n"


##################
## Update Bagel ##
##################

cd "$(dirname "${BASH_SOURCE}")"
git pull origin master


#################
## Bagel Magic ##
#################

source ./utils      # Utility functions
source ./bootstrap  # Base configuration
source ./shell      # Update and set bash as the shell
source ./brew       # Install homebrew components
source ./ruby       # Set up ruby environment
source ./node       # Set up node environment
source ./python     # Set up python environment
source ./cask       # Install common applications
source ./osx        # Set some nice OSX defaults
source ./dots       # Move dot files to home dir


printf "\n\n\n#########################\nDONE\n#########################\n\n\n"
