#!/usr/bin/env bash

# This script is heavily influenced by the laptop project from the great
# thoughtbot team and the fantastic Mathias Bynens' dot files. Many thanks
# to both. Checkout their repos here:
#
# - https://github.com/thoughtbot/laptop
# - https://github.com/mathiasbynens/dotfiles



###########################
## Sudo | Error Handling ##
###########################

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# Kill execution if something goes wrong. TODO: exit more gracefully.
trap 'ret=$?; test $ret -ne 0 && printf "failed\n\n" >&2; exit $ret' EXIT
set -e

# Letting you know bagel started
printf "\n\n\n#########################\nSTART\n#########################\n\n\n"


##################
## Update Bagel ##
##################

cd "$(dirname "${BASH_SOURCE}")"
git pull origin master


#################
## Bagel Magic ##
#################

source ./recipes/utils      # Utility functions
source ./recipes/bootstrap  # Base configuration
source ./recipe/shell       # Update and set bash as the shell
source ./recipes/brew       # Install homebrew components
source ./recipes/ruby       # Set up ruby environment
source ./recipes/node       # Set up node environment
source ./recipes/python     # Set up python environment
source ./recipes/cask       # Install common applications
source ./recipes/osx        # Set some nice OSX defaults
source ./recipes/dots       # Move dot files to home dir


printf "\n\n\n#########################\nDONE\n#########################\n\n\n"
